# ML stroke prediction - Logistic Regression
dataset link: https://www.kaggle.com/datasets/fedesoriano/stroke-prediction-dataset?resource=download

## Classification of stroke or no-stroke

For the first implementation of Machine Learning on this dataset we are using Logistic Regression

In [1]:
# used for manipulating directory paths
import os

# Scientific and vector computation for python
import numpy as np
np.set_printoptions(suppress=True)

import csv
import sys

# Plotting library
from matplotlib import pyplot

# Optimization module in scipy
from scipy import optimize

# will be used to load MATLAB mat datafile format
from scipy.io import loadmat

# we use pandas to import a comma-seperated values dataset
import pandas as pd

# tells matplotlib to embed plots within the notebook
%matplotlib inline

### First importing the dataset and small conversions

For the first implementation we're just using a limited set of features for the model.

In [2]:
#  training data stored in arrays X, y
#df = pd.read_csv(os.path.join('data', 'healthcare-dataset-stroke-data.csv'))
#X = pd.DataFrame(df, columns=['age', 'hypertension', 'heart_disease', 'avg_glucose_level']).to_numpy()
#X = np.around(X, 5)
#print("X: ")
#print(X)

#y = pd.DataFrame(df, columns=['stroke']).to_numpy()
#y = np.around(y, 5)
#y.reshape(5110)
#print("y: ")
#print(y)
 
data = pd.read_csv(os.path.join('data', 'healthcare-dataset-stroke-data.csv'))

data.head(10)

data.drop("id", axis = 1, inplace = True)
data.drop("gender", axis = 1, inplace = True)
data.drop("ever_married", axis = 1, inplace = True)
data.drop("work_type", axis = 1, inplace = True)
data.drop("Residence_type", axis = 1, inplace = True)
data.drop("bmi", axis = 1, inplace = True)
data.drop("smoking_status", axis = 1, inplace = True)

print(data)

       age  hypertension  heart_disease  avg_glucose_level  stroke
0     67.0             0              1             228.69       1
1     61.0             0              0             202.21       1
2     80.0             0              1             105.92       1
3     49.0             0              0             171.23       1
4     79.0             1              0             174.12       1
...    ...           ...            ...                ...     ...
5105  80.0             1              0              83.75       0
5106  81.0             0              0             125.20       0
5107  35.0             0              0              82.99       0
5108  51.0             0              0             166.29       0
5109  44.0             0              0              85.28       0

[5110 rows x 5 columns]


The sigmoid function copied from excersise 2. Could be copied later on to a 'library'.

In [16]:
counter_stroke = 0
counter_non_stroke = 0
data_balanced = np.zeros((398,5))
#print(data_balanced.shape)
data_balanced[0:199] = data[0:199]
data_balanced[199:398] = data[249:448]
print(data_balanced[195:205])
for i in range(398):
    if data_balanced[i, 4] == 1:
        counter_stroke += 1
    else:
        counter_non_stroke += 1
        
print(counter_stroke)
print(counter_non_stroke)

[[ 59.     0.     0.   200.62   1.  ]
 [ 70.     1.     0.   242.52   1.  ]
 [ 69.     0.     0.    93.81   1.  ]
 [ 79.     0.     0.   114.77   1.  ]
 [  3.     0.     0.    95.12   0.  ]
 [ 58.     1.     0.    87.96   0.  ]
 [  8.     0.     0.   110.89   0.  ]
 [ 70.     0.     0.    69.04   0.  ]
 [ 14.     0.     0.   161.28   0.  ]
 [ 47.     0.     0.   210.95   0.  ]]
199
199


In [17]:
X = data.drop(['stroke'], axis=1).values
y = data['stroke'].values

print("Xshape: ")
print(X.shape)
print("Yshape: ")
print(y.shape)

print("X: ")
print(X)

print("y: ")
print(y)

Xshape: 
(5110, 4)
Yshape: 
(5110,)
X: 
[[ 67.     0.     1.   228.69]
 [ 61.     0.     0.   202.21]
 [ 80.     0.     1.   105.92]
 ...
 [ 35.     0.     0.    82.99]
 [ 51.     0.     0.   166.29]
 [ 44.     0.     0.    85.28]]
y: 
[1 1 1 ... 0 0 0]
