# ML stroke prediction - Logistic Regression
dataset link: https://www.kaggle.com/datasets/fedesoriano/stroke-prediction-dataset?resource=download

## Classification of stroke or no-stroke

For the first implementation of Machine Learning on this dataset we are using Logistic Regression

In [2]:
# used for manipulating directory paths
import os

# Scientific and vector computation for python
import numpy as np
np.set_printoptions(suppress=True)

import csv

# Plotting library
from matplotlib import pyplot

# Optimization module in scipy
from scipy import optimize

# will be used to load MATLAB mat datafile format
from scipy.io import loadmat

# we use pandas to import a comma-seperated values dataset
import pandas as pd

# tells matplotlib to embed plots within the notebook
%matplotlib inline

### First importing the dataset and small conversions

For the first implementation we're just using a limited set of features for the model.

In [3]:
#  training data stored in arrays X, y
#df = pd.read_csv(os.path.join('data', 'healthcare-dataset-stroke-data.csv'))
#X = pd.DataFrame(df, columns=['age', 'hypertension', 'heart_disease', 'avg_glucose_level']).to_numpy()
#X = np.around(X, 5)
#print("X: ")
#print(X)

#y = pd.DataFrame(df, columns=['stroke']).to_numpy()
#y = np.around(y, 5)
#y.reshape(5110)
#print("y: ")
#print(y)
 
data = pd.read_csv(os.path.join('data', 'healthcare-dataset-stroke-data.csv'))

data.head(10)

data.drop("id", axis = 1, inplace = True)
data.drop("gender", axis = 1, inplace = True)
data.drop("ever_married", axis = 1, inplace = True)
data.drop("work_type", axis = 1, inplace = True)
data.drop("Residence_type", axis = 1, inplace = True)
data.drop("bmi", axis = 1, inplace = True)
data.drop("smoking_status", axis = 1, inplace = True)

print(data)

X = data.drop(['stroke'], axis=1).values
y = data['stroke'].values

print("Xshape: ")
print(X.shape)
print("Yshape: ")
print(y.shape)

print("X: ")
print(X)

print("y: ")
print(y)

       age  hypertension  heart_disease  avg_glucose_level  stroke
0     67.0             0              1             228.69       1
1     61.0             0              0             202.21       1
2     80.0             0              1             105.92       1
3     49.0             0              0             171.23       1
4     79.0             1              0             174.12       1
...    ...           ...            ...                ...     ...
5105  80.0             1              0              83.75       0
5106  81.0             0              0             125.20       0
5107  35.0             0              0              82.99       0
5108  51.0             0              0             166.29       0
5109  44.0             0              0              85.28       0

[5110 rows x 5 columns]
Xshape: 
(5110, 4)
Yshape: 
(5110,)
X: 
[[ 67.     0.     1.   228.69]
 [ 61.     0.     0.   202.21]
 [ 80.     0.     1.   105.92]
 ...
 [ 35.     0.     0.    82.99]
 [

In [24]:
from sklearn.model_selection import train_test_split #Split the matrixes into train and test subsets.

X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.20, random_state=0,shuffle=True, stratify=y)


### check percentage of strokes in set

In [26]:
y_count = 0
for i in y_train:
    if i == 1:
        y_count += 1
        
print(((y_count)/(y_train.size))*100)

y_count = 0
for i in y_test:
    if i == 1:
        y_count += 1
        
print(((y_count)/(y_test.size))*100)

print(y_train.shape)
print(y_test.shape)

4.867906066536203
4.892367906066536
(4088,)
(1022,)


# Dit werkt!!!!